[package]

name = "hematite"
version = "0.0.8"
license = "MIT"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["minecraft", "piston", "client"]
description = "A simple Minecraft client"
repository = "https://github.com/PistonDevelopers/hematite.git"
homepage = "http://hematite.piston.rs"

[profile.release]
opt-level = 2
debug = false

[[bin]]

name = "hematite"
path = "src/main.rs"

[dependencies]
byteorder = "0.4"
camera_controllers = "0.10.0"
docopt = "0.6.76"
flate2 = "0.2"
fps_counter = "0.2.0"
gfx = "0.8.0"
gfx_device_gl = "0.7.0"
image = "0.6.0"
libc = "0.2.2"
memmap = "0.2.2"
piston = "0.17.0"
piston3d-gfx_voxel = "0.6.0"
pistoncore-sdl2_window = "0.23.0"
rustc-serialize = "0.3"
sdl2 = "0.13.0"
shader_version = "0.2.0"
time = "0.1.34"
vecmath = "0.2.0"
zip = "0.1.14"
